EoRImaging/eppsilon

- dictionary.md
- ps_core/kspace_rebinning_1d.pro
- ps_core/ps_main_plots.pro
- ps_core/ps_power.pro
- ps_wrappers/ps_wrapper.pro
addressing issue #15.
@nicholebarry can you test that this works as expected?
> make 2d power spectra with voxel mask from 1d power spectra

- dictionary.md
- ps_core/ps_kcube.pro
- ps_core/ps_main_plots.pro
- ps_core/ps_power.pro
- ps_wrappers/ps_wrapper.pro
> Error by default if no beam integral in obs structure, add override keyword

- ps_core/fhd_file_setup.pro
Includes backwards compatibility for the beam_integral keyword.
> Change beam_integral to primary_beam_sq_area

- ps_core/fhd_file_setup.pro
- ps_wrappers/ps_wrapper.pro
> fix a couple of bugs introduced on last PR

- ps_core/ps_kcube.pro
> fix for uv_avg and uv_img_clip with derived cubes

- ps_compare/compare_plot_prep.pro
> get extension from plot_options structure

- dictionary.md
- ps_setup/create_file_tags.pro
- ps_setup/create_uvf_options.pro
- ps_utils/choose_pix_ft.pro
- ps_wrappers/ps_diff_wrapper.pro
- ps_wrappers/ps_ratio_wrapper.pro
- ps_wrappers/ps_wrapper.pro
@nicholebarry @adampbeardsley this is the new PR to support using the full image without a window function. Please take a look/test it to make sure it does what you need.
> Add option to use the full image size with no window function

- ps_core/ps_image_to_uvf.pro
- ps_core/ps_main_plots.pro
- ps_setup/fhd_file_setup.pro
- ps_utils/healpix_rot.pro
> fix several error handling issues that lead to confusing error & warning messages

- ps_wrappers/ps_filenames.pro
> fix for logic loop with refresh_info

- ps_core/ps_image_to_uvf.pro
- ps_utils/choose_pix_ft.pro
@wenyang-li this should fix the bug you found.
> Fix bug in backwards compatibility code, add warnings

- ps_core/ps_kcube.pro
Also add a bunch of checks along the way
> fix calculation of zero mode and shifting to work for even & odd n_freq

- ps_wrappers/get_folder.pro
> make expand_path call in get_folder work with multiple folder names

- ps_utils/z_mpc.pro
> changing floats to doubles for precision in z_mpc.pro

- ps_core/ps_kcube.pro
- ps_utils/z_mpc.pro
Updated values to be more precise. Addresses #99 and #102
> updated hyperfine freq and c

- ps_core/ps_kcube.pro
Make the rotation angle calculation more robust against zeros in the denominator.
Also rework the std_power implementation: just don't rotate between sin & cos
> Improve LS implementation

- ps_plotting/kpower_2d_plots.pro
> Fix bug where the noise_meas keyword was orphaned

- ps_core/ps_kcube.pro
> true dft formula change

- ps_wrappers/ps_filenames.pro
@PyxieLouStar see if this fixes your problem.
> make filename polarization regex more specific

- ps_compare/compare_plot_prep.pro
- ps_core/ps_main_plots.pro
- ps_plotting/ps_difference_plots.pro
> Fix coarse band harmonic flagging in diff plots

- dictionary.md
- ps_core/ps_kcube.pro
- ps_setup/create_ps_options.pro
- ps_wrappers/ps_wrapper.pro
also add top-level keyword to control using true z or z from regular freq spacing in dft.
fixes #103
> properly match sigma calculation to data if we do a DFT

- ps_wrappers/az_ps_job.pro
Add a wrapper to ps_wrappers for running slurm jobs on azure.
> Add azure ps wrapper

- ps_compare/compare_plot_prep.pro
- ps_wrappers/ps_diff_wrapper.pro
I've added the ability to specify the kperp range in units of lambda to the difference plots. This was useful for me to zoom in on a particular region. It could be useful for someone else too.
> Adding some functionality to 2D difference plots

- ps_core/ps_kcube.pro
- ps_setup/create_ps_options.pro
- ps_setup/fhd_file_setup.pro
- ps_wrappers/ps_wrapper.pro
Add an option to save sum cubes in ps_kcube. Currently 2d sum slices can be saved; this allows for saving the 3d cube.
> implement option to save_sum_cube
