EoRImaging/eppsilon

ps_core/fhd_file_setup.pro
This attempts to fix the bug reported in issue #29 where the weights were contaminated with NaNs if there was missing data. 
I took it on thinking it was an FHD issue, since I didn't look too closely at the repo, but hopefully my changes reflect the original code's intent.
=> Issue#29: Fix NaN weights from missing visibilities.

ps_setup/fhd_file_setup.pro
Fixes a problem where the propagated error was too high. This problem was introduced in commit cc6dcd because the denominator was pulled out of the square root.
=> fix vis noise calculation

ps_core/kspace_rebinning_2d.pro, ps_core/ps_kcube.pro
Fix an bug in how k parallel values are calculated for an odd number of frequencies that lead to ugly horizontal striping in the 2d power spectrum plots.
=> Odd freq fix

ps_compare/compare_plot_prep.pro, ps_compare/ps_differences.pro, ps_core/ps_image_to_uvf.pro, ps_core/ps_kcube.pro, ps_core/ps_main_plots.pro, ps_core/ps_power.pro, ps_setup/fhd_file_setup.pro, ps_utils/check_old_path.pro, ps_wrappers/ps_filenames.pro
This branch reorganizes the output of eppsilon into the following folders:
* ps
* data
* uvf_cubes
* slices
* kspace_cubes
* slices
* beams
* 2d_binning
* from_1d
* 1d_binning (includes kperp/kpar files & kpar=0 files)
* plots
* slices
* 2d_binning
* from_1d
* 1d_binning
* bin_histograms
It is not yet backwards compatible, I have some questions about what users want for backwards compatibility. I think there are two options:
1. When eppsilon is called on an old folder it can reorganize that folder according to this structure. If we do this, the easiest implementation will only move the files associated with the run it's called for, so if there are files generated by runs using different keyword settings, those files would not be moved until eppsilon is re-run with those settings. If this …
=> Do Not Merge: Reorganize output into logical subfolders

ps_core/ps_kcube.pro
Fix the normalization of the k parallel = 0 bin when `ave_removal` is used with a spectral window function.
fixes #63
=> Ave remove fix

dictionary.md, ps_setup/create_uvf_options.pro, ps_utils/choose_pix_ft.pro
Fix errors associated with image window sizes larger than 1
Don't use image window sizes for non-Tukey windows
Improve warnings for applying image windows to small cubes
Fixes #76
=> Fix image window

dictionary.md, ps_core/make_slices.pro, ps_core/ps_binning.pro, ps_core/ps_kcube.pro, ps_core/ps_main_plots.pro, ps_core/ps_power.pro, ps_wrappers/ps_wrapper.pro
added `no_binning` and `save_slices` options:
- setting `no_binning` will result in no 1 or 2D binning being performed
- setting `save_slices=0` will result in no slices being saved
These two options should make it possible to significantly reduce the number of files generated in an eppsilon run.
fixes #73
=> Add options to limit the number of files produced

ps_core/ps_main_plots.pro, ps_setup/create_file_tags.pro, ps_setup/create_uvf_options.pro, ps_utils/choose_pix_ft.pro, ps_wrappers/ps_diff_wrapper.pro, ps_wrappers/ps_ratio_wrapper.pro, ps_wrappers/ps_wrapper.pro
This adds an `image_clip` option, the old default behavior was to use the image clip (small image). This is now an option which is defaulted to off so that the full image is used with the standard uv pixel size.
There is also a `full_image` option, which this PR does not change, which uses the full image and smaller uv pixels set by the size of the image. Using the standard uv pixel size (the new default) means that the pixels are close to uncorrelated, which is the assumption in the rest of the code and also makes it run much faster.
=> Add image_clip option, default to using the full image is used with the standard uv pixel size

ps_core/ps_kcube.pro
Change cos and sin arrays to hold doubles.
Here is a difference between master and changing to doubles (no LS rotation done for simplicity). No significant changes, but perhaps a better estimation of the first coarse band at roughly the EoR level.
=> change arrays to doubles

ps_setup/fhd_file_setup.pro
Fixes a bug reported by Zheng, he confirmed it solved the problem.
=> ensure uvf_savefilebase has the right dimensionality when n_type is 1

ps_core/ps_kcube.pro
If there were null frequencies in the uvf data cube, the uvf_input code would fail. Null frequencies are possible with typical MWA data if no frequency averaging is done. 
This code has been tested.
=> uvf null pointers handled

ps_wrappers/enterprise_folder_locs.pro
On line 35, folder names needs to be indexed to avoid an error when using wrappers where multiple file names are specified
=> Indexing bug 

ps_core/ps_image_to_uvf.pro, ps_core/ps_kcube.pro, ps_core/single_cube_dft.pro, ps_setup/casa_file_setup.pro, ps_setup/fhd_file_setup.pro, ps_setup/rts_file_setup.pro
The observation volume calculation was being performed over the full band. If a subband is chosen, it should be calculated only over that subband. 
This does effect the published limits. Thankfully, it is small. For example, lowest limit from Barry et al 2019b for z=7 (lower freqs than average) was 3890.4814 mK^2, but should be 3745.1896 mK^2. I think that means that Wenyang's limits from the z=6.5 band (high freqs than average) should be a little higher than they should be.
I also removed some backwards-compatibility stuff that is probably no longer necessary.
=> Observation volume calculation

ps_setup/create_ps_options.pro
Add the beam approx option to the ps_options structure. 
I've added it as a stable option (always present).
=> add beam approx to structure

dictionary.md, ps_core/ps_kcube.pro, ps_plotting/ps_ratio_plots.pro, ps_setup/create_file_tags.pro, ps_setup/create_ps_options.pro, ps_setup/fhd_file_setup.pro, ps_utils/cosmology_measures.pro, ps_utils/z_mpc.pro, ps_wrappers/ps_diff_wrapper.pro, ps_wrappers/ps_wrapper.pro
Add an option to do a frequency DFT even in the case of even frequency spacing to allow for using the true z values.
Cannot be merged until #119 is.
fixes #123
=> Add freq_dft option

ps_core/ps_image_to_uvf.pro, ps_core/ps_kcube.pro
uvf cubes didn't have the correct freq_ch_range and freq_flags logic. This isn't a widely used option for uvf cubes, but it's nice to have for comparison purposes.
Frequency channel ranges are determined *before* the frequency flags are applied. The data, model, weights, and all beam options must have the same logic. 
Tested and works with uvf cubes and Healpix cubes with both freq ranges/flags. There was stale Healpix logic (freq flags before freq channel ranges) that has been removed.
=> uvf cubes and freq range/flags

ps_setup/fhd_file_setup.pro
Strange IDL behaviour incoming...
Even if the values within a struct are double, the summation performed over the full struct is not double automatically.
For example, total(obs_arr.n_vis) where obs_arr is a struct array of 160 observations gives 1799498624. The true answer is 1799498646. If you force the total to perform double summation with /double, you get the correct answer. If you were to perform the summation looping over the struct array (i.e. for i=0, 159 do total += obs_arr[i].n_vis) you get the correct answer.
Affects metadata reporting and an extremely small change in some of the normalisation calculations of the beam integral.
=> force double summation

ps_core/ps_main_plots.pro, ps_setup/fhd_file_setup.pro
This PR resolves #139 when the user explicitly passes `pol_inc = ['xx','yy','xy','yx']`. However, we might want to add functionality to allow eppsilon to process only XX and YY cubes when the UVF cubes contain all 4 polarizations. It would also be best to fix the default behavior so the run doesn't error when `pol_inc` is not set.
=> Run in 4pol mode with uvf inputs

ps_core/make_slices.pro
This PR resolves a bug in which constant-U slices are compared against constant-V slices. The bug causes runs with extensive zero-padding in the UV plane to error.
=> Slice power check bug fix

ps_core/ps_kcube.pro, ps_plotting/cube_images.pro, ps_setup/fhd_file_setup.pro
This cleans up a bunch of minor bugs that broke things in recent runs:
- properly detect npol if no polnames in filenames
- handle descending time order in time resolution calculation
- Always use the vis_sigma calculated by FHD if it is available
- Only use the file basename when parsing polarizations out of filenames
- properly handle fully flagged frequencies in cube image plotting
- Fix a bug when we only have one file (no even/odd split)
- Properly handle a null pointer in for `vis_noise` in the obs structure (happens with only one time).
- Fix a bug in beam integral handling for single times (no vis_noise in obs structure), also generally clean up beam integral handling.
=> Fix edge cases

ps_setup/fhd_file_setup.pro
I introduced this in #154, this solution works for the normal case and the edge cases tested in that PR.
=> Fix a bug in getting vis noise from obs_arr
